copy %1%2.dll ..\..\Deadliness\Unity\Assets\Dlls /Y
copy %1%2.pdb ..\..\Deadliness\Unity\Assets\Dlls /Y
copy %1%2.dll ..\..\Deadliness\Project\Lib /Y
copy %1%2.pdb ..\..\Deadliness\Project\Lib /Y
copy %1%2.dll ..\..\Lockstep\Unity\Assets\Dlls /Y
copy %1%2.pdb ..\..\Lockstep\Unity\Assets\Dlls /Y
copy %1%2.dll ..\..\Lockstep\Project\Lib /Y
copy %1%2.pdb ..\..\Lockstep\Project\Lib /Y
copy %1%2.dll ..\..\Lockstep\Project\Bin /Y
copy %1%2.pdb ..\..\Lockstep\Project\Bin /Y